export const lbRouterAbi = [
  {
    type: 'function',
    name: 'addLiquidityUniform',
    inputs: [
      { name: 'tokenX', type: 'address' },
      { name: 'tokenY', type: 'address' },
      { name: 'binStep', type: 'uint16' },
      { name: 'amountX', type: 'uint256' },
      { name: 'amountY', type: 'uint256' },
      { name: 'activeBinId', type: 'uint24' },
      { name: 'binRange', type: 'uint24' },
      { name: 'to', type: 'address' },
      { name: 'deadline', type: 'uint256' },
    ],
    outputs: [{ name: 'shares', type: 'uint256[]' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addLiquiditySpot',
    inputs: [
      { name: 'tokenX', type: 'address' },
      { name: 'tokenY', type: 'address' },
      { name: 'binStep', type: 'uint16' },
      { name: 'amountX', type: 'uint256' },
      { name: 'amountY', type: 'uint256' },
      { name: 'binId', type: 'uint24' },
      { name: 'to', type: 'address' },
      { name: 'deadline', type: 'uint256' },
    ],
    outputs: [{ name: 'shares', type: 'uint256[]' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'swapExactTokensForTokens',
    inputs: [
      { name: 'tokenIn',      type: 'address' },
      { name: 'tokenOut',     type: 'address' },
      { name: 'binStep',      type: 'uint16'  },
      { name: 'amountIn',     type: 'uint256' },
      { name: 'minAmountOut', type: 'uint256' },
      { name: 'to',           type: 'address' },
      { name: 'deadline',     type: 'uint256' },
    ],
    outputs: [{ name: 'amountOut', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'removeLiquidity',
    inputs: [
      { name: 'tokenX', type: 'address' },
      { name: 'tokenY', type: 'address' },
      { name: 'binStep', type: 'uint16' },
      { name: 'binIds', type: 'uint24[]' },
      { name: 'sharesPerBin', type: 'uint256[]' },
      { name: 'minAmountX', type: 'uint256' },
      { name: 'minAmountY', type: 'uint256' },
      { name: 'to', type: 'address' },
      { name: 'deadline', type: 'uint256' },
    ],
    outputs: [
      { name: 'amountX', type: 'uint256' },
      { name: 'amountY', type: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
] as const
